### PR TITLE
Trace log (SLF4J+Logback)

### PR DESCRIPTION
**Pull request by pepgrifell**

### CODE REVIEW

**Comment by pepgrifell** [comment]
> Do we really need the qualifier SLF4JLogger ?

No, I had an error deploying to Wildfly without it but now I have been able to remove it

**Comment by pepgrifell** [comment]
> @pepgrifell One question:
> Can logback.xml be outside the ear/war?. I would be nice to be an external file in order to change the log configuration without modify the ear or war.

I'll check it.

**Comment by pepgrifell** [comment]
I have tested to have logback.xml outside WAR and it is possible although we need to do some modifications in Wilfly configuration files.
It has been documented in LOGGING.md file, based on this blog:
http://loctranhoang.blogspot.com/2017/08/slf4j-with-logback-in-wildfly10.html+

**Comment by vinyulis** [comment]
@pepgrifell Thanks for the info!!

**Pull request merged**
